# config.yml
collectors:
  enabled: cpu,cs,logical_disk,net,os,service,system,textfile,scheduled_task,process,mssql,memory
collector:
  service:
    services-where: Name='windows_exporter'
  scheduled_task:
    blacklist: /Microsoft/.+
log:
  level: debug
scrape:
  timeout-margin: 0.5
telemetry:
  addr: ":9182"
  path: /metrics
